/* 
 * File:   server.h
 *      Defines a set of server (mpi master) side functions and types.
 *      
 * Author: TBD
 *
 * 
 * Created on 13. Januar 2015, 11:29
 */

#ifndef PB_SERVER_H
#define	PB_SERVER_H

#ifdef	__cplusplus
extern "C" {
#endif

    /**
     * Type definition for server meta data.
     */
    struct ServerContext {
        /**
         * The number of clients used by the server.
         */
        int numClients;
        /**
         * The first password to be generated by one of the clients.
         */
        char* startPassword;
        /**
         * The last password to be generated by one of the clients.
         */
        char* endPassword;
        /**
         * The alphabet to be used to generate new passwords. p &isin; A*  <br>( p -> new password; A ->  alphabet)
         */
        char* alphabet;

        int numPasswords;


    };

    typedef struct ServerContext ServerContext;

    ServerContext initializeWithPW(int numWorkers, char* startPW, char* endPW);
    ServerContext initializeWithLenght(int numWorkers, char* startPW, ulong numPasswords);
    /**
     * Counts up a given password using the default alphabet.
     * @param in The input password.
     * @param outPass The output password. Caller must take care of allocation (may defer in length by one) and cleaning up.
     */
    void nextPass(char* in, char* outPass);
    /**
     * Get the index number for a given <code>string</code> using the default <code>alphabet</code>.
     * @param string The input to convert to a number.
     * @return The counting index number of the given <code>string</code>. 
     * It can be considered as an index value of the <code>string</code> within the password generation algorithm's generation index.
     * (That is, the input of 'aaaa' and 'aa' produce different results.)
     */
    ulong toNumberIndefaultAlphabet(char* string);
    
    /**
     * Calculate the number of elements between <code>pw1</code> and <code>pw2</code>
     * @param pw1
     * @param pw2
     * @return 
     */
    ulong getPasswordDiff(char* pw1,char* pw2);

    void getPasswordAtRelativeOffset(char* offsetPw, char* result, ulong targetDifference);


#ifdef	__cplusplus
}
#endif

#endif	/* PB_SERVER_H */

